"""Updated Customer table with phone number section

Revision ID: b36d58834c54
Revises: ebd97d3d00fa
Create Date: 2024-12-05 15:46:53.480342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36d58834c54'
down_revision = 'ebd97d3d00fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
